apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: self-order-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: self-order-management
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30