apiVersion: v1
kind: Service
metadata:
  name: self-order-management
  labels:
    app: self-order-management
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31300
  selector:
    app: self-order-management
