version: '3.7'

services:
  api:
    image: tech-challenge:latest
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_ENDPOINT=db:5432
      - DB_NAME=selforder
      - DB_USERNAME=selforder
      - DB_PASSWORD=self@Order123!
      - ADMIN_ACCESS_TOKEN=token
      - MOCK_PAYMENT_PROVIDER=true
      - MP_TOKEN=token
      - MP_USER_ID=userId
      - MP_POS_ID=postId
      - MP_WEBHOOK_BASE_URL=webhookBaseUrl
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:15.4
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=selforder
      - POSTGRES_USER=selforder
      - POSTGRES_PASSWORD=self@Order123!
    ports:
      - "5432:5432"
    restart: always

volumes:
  db:
    driver: local
