spring:
  application:
    name: self-order-management
  datasource:
    url: jdbc:postgresql://${DB_ENDPOINT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
        globally_quoted_identifiers: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ygM5FRn7D
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ygM5FRn7D/.well-known/jwks.json

admin:
  access-token: ${ADMIN_ACCESS_TOKEN}

payment-provider:
  mock: ${MOCK_PAYMENT_PROVIDER}

mercadopago:
  api:
    url: https://api.mercadopago.com
    token: ${MP_TOKEN}
    userId: ${MP_USER_ID}
  integration:
    posId: ${MP_POS_ID}
    webhookBaseUrl: ${MP_WEBHOOK_BASE_URL}
