spring:
  application:
    name: self-order-management
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/selforder
    username: selforder
    password: self@Order123!

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        globally_quoted_identifiers: true

self-order:
  admin:
    access-token: token

mercadopago:
  api:
    url: https://api.mercadopago.com
    token: REPLACE
    userId: REPLACE
  integration:
    posId: REPLACE
    webhookBaseUrl: REPLACE
