spring:
  application:
    name: self-order-management
  flyway:
    baseline-on-migrate: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        globally_quoted_identifiers: true

self-order:
  admin:
    access-token: token

mercadopago:
  api:
    url: https://api.mercadopago.com
    token: ${MP_TOKEN}
    userId: ${MP_USER_ID}
  integration:
    posId: ${MP_POST_ID}
    webhookBaseUrl: ${MP_WEBHOOK_BASE_URL}
