apiVersion: v1
kind: Service
metadata:
  name: self-order-management-load-balancer-service
spec:
  type: LoadBalancer
  selector:
    app: self-order-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
