apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-order-management
  labels:
    app: self-order-management
spec:
  replicas: 1
  selector:
      matchLabels:
        app: self-order-management
  template:
      metadata:
        labels:
          app: self-order-management
      spec:
        containers:
        - name: self-order-management
          image: 202062340677.dkr.ecr.sa-east-1.amazonaws.com/self-order-management:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 30
            failureThreshold: 10
            initialDelaySeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 30
            failureThreshold: 10
            initialDelaySeconds: 20
            timeoutSeconds: 5
          env:
              - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret-config
                    key: password
              - name: SPRING_DATASOURCE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret-config
                    key: user
              - name: DATABASE_NAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret-config
                    key: db
              - name: SPRING_DATASOURCE_URL
                value: jdbc:postgresql://postgres:5432/${DATABASE_NAME}
              - name: MP_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: self-order-management-secret-config
                    key: mp-token
              - name: MP_USER_ID
                valueFrom:
                  secretKeyRef:
                    name: self-order-management-secret-config
                    key: mp-user-id
              - name: MP_POST_ID
                valueFrom:
                  secretKeyRef:
                    name: self-order-management-secret-config
                    key: mp-post-id
              - name: MP_WEBHOOK_BASE_URL
                valueFrom:
                  secretKeyRef:
                    name: self-order-management-secret-config
                    key: mp-webhook-base-url
