@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Diagrama de Contexto C4

Person_Ext(customer, "Cliente", "cliente do restaurante,\ncom ou sem cadastro")
Person(admin, "Administrador", "administrador do restaurante")
System(system, "Sistema de Autoatendimento de Restaurante", "permite fazer e acompanhar pedidos, além de gerenciar pedidos, clientes, produtos, estoque, etc")

System_Ext(payment_system, "Mercado Pago", "Sistema de pagamento")

Rel(customer, system, "usa")
Rel(customer, payment_system, "paga")
Rel(admin, system, "administra")
Rel(admin, payment_system, "acessa")
Rel_Neighbor(system, payment_system, "usa")
Rel_Neighbor(payment_system, system, "notifica")

@enduml
