@startuml

title Payment Sequence Diagram

actor Customer as customer
participant API as api
participant "MP API" as mp_api
participant "MP Notificator" as mp_notificator
database "API DB" as db

autonumber

customer -> api: place an order
activate api
api -> db: save CREATED order
activate db
db -> api: order number
deactivate db
api -> mp_api: create external order
activate mp_api
mp_api --> mp_notificator: create IPN for merchant order
activate mp_notificator
mp_api -> api: QR Code + store order ID
deactivate mp_api
api -> db: save PENDING payment
api -> db: update order: PENDING
api -> customer: return QR Code
deactivate api
mp_notificator -> api: notify merchant order to webhook
activate api
api -> db: update payment record w/ merchant order ID
api -> mp_notificator: return 200 OK
deactivate api
deactivate mp_notificator
customer -> mp_api: pay with QR Code
activate mp_api
mp_api --> mp_notificator: create IPN for payment
activate mp_notificator
mp_api -> customer: success
deactivate mp_api
mp_notificator -> api: notify payment to webhook
activate api
api -> mp_api: check merchant order status
activate mp_api
mp_api -> api: merchant order status
deactivate mp_api
api -> db: update payment: CONFIRMED
api -> db: update order: CONFIRMED
api -> mp_notificator: return 200 OK
deactivate mp_notificator

@enduml
