@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class customer {
   customer_name: varchar(255)
   customer_email: varchar(255)
   customer_phone: varchar(255)
   customer_address: varchar(1000)
   customer_document: varchar(20)
}
class order {
   order_date: date
   order_customer_nickname: varchar(255)
   order_customer_document: varchar(20)
   order_status: varchar(255)
   order_total: numeric(15,2)
   order_number: integer
}
class order_item {
   order_item_product_number: integer
   order_item_order_number: integer
   order_item_id: integer
}
class payment {
   payment_external_id: uuid
   payment_created_at: timestamp
   payment_status: text
   payment_status_changed_at: timestamp
   payment_order_number: integer
}
class product {
   product_name: varchar(255)
   product_type: varchar(255)
   product_cost_price: numeric(15,2)
   product_description: varchar(255)
   product_min_sub_item: integer
   product_max_sub_item: integer
   product_category: varchar(255)
   product_number: integer
}
class product_sub_item {
   product_sub_item_product_id_parent: integer
   product_sub_item_product_id_sub: integer
   product_sub_item_id: integer
}
class stock {
   stock_quantity: bigint
   stock_unit: varchar(255)
   stock_product_number: integer
}

order             -[#595959,plain]-^  customer         : "order_customer_document:customer_document"
order_item        -[#595959,plain]-^  order            : "order_item_order_number:order_number"
order_item        -[#595959,plain]-^  product          : "order_item_product_number:product_number"
payment           -[#595959,plain]-^  order            : "payment_order_number:order_number"
product_sub_item  -[#595959,plain]-^  product          : "product_sub_item_product_id_parent:product_number"
product_sub_item  -[#595959,plain]-^  product          : "product_sub_item_product_id_sub:product_number"
stock             -[#595959,plain]-^  product          : "stock_product_number:product_number"
@enduml
