version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./self-order_schema.sql:/docker-entrypoint-initdb.d/self-order_schema.sql
    environment:
      - POSTGRES_DB=selforder
      - POSTGRES_USER=selforder
      - POSTGRES_PASSWORD=self@Order123!
    ports:
      - "5432:5432"

volumes:
  db:
    driver: local
