name: "App"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/app.yml
      - 'Fase-1/API/self-order-management/**'
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/app.yml
      - 'Fase-1/API/self-order-management/**'

jobs:
  app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify
        working-directory: ./Fase-1/API/self-order-management/
        run: mvn verify -DskipITs=false -q

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::202062340677:role/TechChallengeWebsiteDeployer
          aws-region: sa-east-1
