name: "App"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/app.yml
      - 'src/**'
      - pom.xml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/app.yml
      - 'src/**'
      - pom.xml

jobs:
  app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify
        run: mvn verify -DskipITs=false -q
