name: OpenAPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  openapi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate OpenAPI
        run: mvn clean verify -DskipOpenAPIGen=false -q

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync S3 bucket
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: aws s3 cp ./target/openapi.json s3://${{ vars.AWS_S3_BUCKET_NAME }}
        
      - name: Push OpenAPI to Postman
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: davidespihernandez/push-openapi-to-postman@v1
        with:
          path-to-definition: ./target/openapi.json
          postman-api-key: ${{ secrets.POSTMAN_API_KEY }}
          api-id: ${{ vars.POSTMAN_API_ID }}
          api-path-to-file-name: index.json
          version-name: '1.0.0'
