name: "OpenAPI"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/openapi.yml
      - 'Fase-1/API/self-order-management/**'
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/openapi.yml
      - 'Fase-1/API/self-order-management/**'

jobs:
  app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate OpenAPI
        working-directory: ./Fase-1/API/self-order-management/
        run: mvn clean verify -DskipOpenAPIGen=false -q

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::202062340677:role/TechChallengeWebsiteDeployer
          aws-region: sa-east-1

      - name: Sync S3 bucket
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: aws s3 cp ./Fase-1/API/self-order-management/target/openapi.json s3://${{ vars.AWS_S3_BUCKET_NAME }}
        
      - name: Push OpenAPI to Postman
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: davidespihernandez/push-openapi-to-postman@v1
        with:
          path-to-definition: ./Fase-1/API/self-order-management/target/openapi.json
          postman-api-key: ${{ secrets.POSTMAN_API_KEY }}
          api-id: ${{ vars.POSTMAN_API_ID }}
          api-path-to-file-name: index.json
          version-name: '1.0.0'
